# Generated by Django 5.1.7 on 2025-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
